project_id = "bvleffevnnugjdwygqyz"

[functions.moneroo-webhook]
verify_jwt = false

[functions.process-moneroo-payment]
verify_jwt = false

[functions.nowpayments-webhook]
verify_jwt = false

[functions.process-nowpayments-payment]
verify_jwt = false

[functions.make-admin]
verify_jwt = false

[functions.retry-payment]
verify_jwt = false

[functions.initiate-payout]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.create-notification]
verify_jwt = false

[functions.setup-default-admin]
verify_jwt = false

[functions.update-admin-credentials]
verify_jwt = true

[functions.update-api-keys]
verify_jwt = true