// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvleffevnnugjdwygqyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2bGVmZmV2bm51Z2pkd3lncXl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDQ4NTYsImV4cCI6MjA3NDU4MDg1Nn0.A3t2QG_Qi57mBinjfg9vTq979jp31b9VDVFEKDOguHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});